using System;
using Keystone.Commands;

namespace Sculptor.Operations
{
    public class PlotPoint : ICommand // a command generated by brushes such as Pencil 
    {
        #region ICommand Members
        public int ID
        {
            get { throw new NotImplementedException(); }
        }

        public CommandState State
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }

        public Amib.Threading.PostExecuteWorkItemCallback Completion
        {
            get { throw new NotImplementedException(); }
        }

        public object Execute()
        {
            throw new NotImplementedException();
        }

        public void UnExecute()
        {
            throw new NotImplementedException();
        }
        #endregion
    }
}
