<html>
	<head>
		<title>$title$</title>
		<link rel="stylesheet" href="styles/style5.css" type="text/css" />
		<link rel="stylesheet" href="js/jquery-ui-1.10.4/themes/base/jquery-ui.css">
		
		<script type='text/javascript' src='js/jquery-latest.min.js'></script>
		<script type='text/javascript' src="js/jquery-ui-1.10.4/ui/jquery-ui.js"></script>
		<script type='text/javascript' src='js/sqllite_tasks.js'></script>
		<script type="text/javascript" src='js/tablesorter/jquery.tablesorter.js'></script> 
		<script type='text/javascript' src='js/cprogress.js'></script>
	</head>
	<body>
		$body$
	</body>
</html>





	