<table cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th id="sorting_asc">Device</th>
			<th id="sorting_desc">Consumption (kW/h)</th>
			<th id="sorting">External power</th>
			<th id="sorting">Regulator</th>
			<th id="sorting">Main breaker</th>
		</tr>
	</thead>
	<tbody>
		$consumers:power_gen_consumers_row()$
	</tbody>
	<tfoot>
		<tr>
			<th>Device</th>
			<th>Consumption (kW/h)</th>
			<th>External power</th>
			<th>Regulator</th>
			<th>Main breaker</th>
		</tr>
	</tfoot>
</table>
