	 <button id="addwaypoint" type="button" onclick="app.ButtonClick(this.id)">Add Waypoint</button> 

	$waypoints$
	
	<!--
	<div class="CSSTableGenerator">
		<table id="taskTable" class="tablesorter">
			<thead>
				<tr>
					<th width="5%"></th>
					<th width="5%"></th>
					<th>Name</th>
					<th>Target</th>
					<th>Created By</th>
					<th>Assigned To</th>
					<th>Status</th>
					<th width="10%"></th> <!-- Delete/Suspend/Cancel if in progress-->
				</tr>
			</thead>
			
			<tbody>
				<tr>
					<td><span class="pr3">3</span></td>
					<td><img src="images/steering_wheel.png" height="16" width="16"/></td>
					<td>Travel to</td>
					<td>Venus</td>
					<td>Cpt. Hypnotron</td>
					<td>Helm</td>
					<td>50%</td>
					<td>
						<img id="edittask" src="images/cog_edit.png" height="16" width="16" onclick="app.ButtonClick(this.id)"/>
						<img id="deletetask" src="images/cog_delete.png" height="16" width="16" onclick="app.ButtonClick(this.id)"/>
					</td>
				</tr>
				<tr>
					<td><span class="pr7">7</span></td>
					<td><img src="images/steering_wheel.png" height="16" width="16"/></td>
					<td>Orbit</td>
					<td>Venus</td>
					<td>Cpt. Hypnotron</td>
					<td>Helm</td>
					<td>0%</td>
					<td>
						<img src="images/cog_edit.png" height="16" width="16"/>
						<a href="#" data-handler="GUILayout_ButtonClick"><img src="images/cog_delete.png" height="16" width="16"/></a>
					</td>
				</tr>
				<tr>
					<td><span class="pr9">9</span></td>
					<td><img src="images/flask.png" height="16" width="16"/></td>
					<td>Astronomical Survey</td>
					<td>Venus</td>
					<td>Cpt. Hypnotron</td>
					<td>Science</td>
					<td>0%</td>
					<td>
						<img src="images/cog_edit.png" height="16" width="16"/>
						<a href="#" data-handler="GUILayout_ButtonClick"><img src="images/cog_delete.png" height="16" width="16"/></a>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
	<-->