<div class="CSSTableGenerator">
<table cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th width="5%" id="sorting_asc"></th>
			<th id="sorting_desc">Command</th>
			<th id="sorting">Orbital Type</th>
			<th id="sorting">Orbital Distance</th>
			<th width="5%" id = "sorting"></th>
			<th width="5%" id = "sorting"></th>
			<th width="5%" id = "sorting"></th>
		</tr>
	</thead>
	<tbody>
		$waypoints:waypoint_row()$
	</tbody>
</table>
</div>