<h3>$componenttypename$</h3>

<table border="0" style="margin: 10px 20px;">
	<tr>
		<td width="96" style="padding: 2px 5px 0 0">
		</td>
		<td>
			Name: Titan [4th Planet]
			<br/>
			System - Sol
			<br/>
			Class: D1 - Rocky Iceball 
			<br/>
			Atmosphere: Nit (77%), Oxy (20%), C Di (1%), Ar (0.7%), Trace (0.3%) (Breathable)
			<br/> 		
			Percent Land: 23.5%
			<br/>
			Hydrosphere: Water Lakes 13.5%, Liquid Methane Oceans 60% 
			<br/>
			Clouds: 37% 
			<br/>
			Mass: 2.52 Earth masses
			<br/> 
			Density: 6331 Kg
			<br/> 
			Radius: 1.52 Earth radius
			<br/> 
			Gravity: 1.08 Earth
			<br/>
			Escape Velocity: 6.18 Km/s
			<br/>
			Magnetic Field: 0.001 Gauss
			<br/>
			Life: Primitive 
			<br/>
			Controlled by: Sol Alliance Since 2245AD
		</td>
	</tr>
</table>
<hr>

<h3>Mining Survey</h3>
<a href="#" class="hide">[hide]</a>
<a href="#" class="show">[show]</a>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
	<thead>
		<tr>
			<th id="sorting_asc">Mineral</th>

			<th id="sorting_desc">Surface Deposits</th>
			<th id="sorting">Mineable</th>
			<th id="sorting">Inaccessible</th>
			<th id="sorting">Grade</th>
		</tr>
	</thead>
	<tbody>

		<tr class="gradeX">
			<td>Trident</td>
			<td>Internet
				 Explorer 4.0</td>
			<td>Win 95+</td>
			<td class="center">4</td>
			<td class="center"><img alt="test..." src="radiationicon"></td>

		</tr>
		<tr class="odd.gradeC">
			<td>Trident</td>
			<td>Internet
				 Explorer 5.0</td>
			<td>Win 95+</td>
			<td class="center">5</td>
			<td class="center">C</td>

		</tr>
		<tr class="even.gradeA">
			<td>Trident</td>
			<td>Internet
				 Explorer 5.5</td>
			<td>Win 95+</td>
			<td class="center">5.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="odd.gradeA">
			<td>Trident</td>
			<td>Internet
				 Explorer 6</td>
			<td>Win 98+</td>
			<td class="center">6</td>
			<td class="center">A</td>

		</tr>
		<tr class="even.gradeA">
			<td>Trident</td>
			<td>Internet Explorer 7</td>
			<td>Win XP SP2+</td>
			<td class="center">7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Trident</td>
			<td>AOL browser (AOL desktop)</td>
			<td>Win XP</td>
			<td class="center">6</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Firefox 1.0</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Firefox 1.5</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Firefox 2.0</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Firefox 3.0</td>
			<td>Win 2k+ / OSX.3+</td>
			<td class="center">1.9</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Camino 1.0</td>
			<td>OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Camino 1.5</td>
			<td>OSX.3+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Netscape 7.2</td>
			<td>Win 95+ / Mac OS 8.6-9.2</td>
			<td class="center">1.7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Netscape Browser 8</td>
			<td>Win 98SE+</td>
			<td class="center">1.7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Netscape Navigator 9</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.0</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.1</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.1</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.2</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.2</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.3</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.3</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.4</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.4</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.5</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.6</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">1.6</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.7</td>
			<td>Win 98+ / OSX.1+</td>
			<td class="center">1.7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Mozilla 1.8</td>
			<td>Win 98+ / OSX.1+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Seamonkey 1.1</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Gecko</td>
			<td>Epiphany 2.20</td>
			<td>Gnome</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 1.2</td>
			<td>OSX.3</td>
			<td class="center">125.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 1.3</td>
			<td>OSX.3</td>
			<td class="center">312.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 2.0</td>
			<td>OSX.4+</td>
			<td class="center">419.3</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>Safari 3.0</td>
			<td>OSX.4+</td>
			<td class="center">522.1</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>OmniWeb 5.5</td>
			<td>OSX.4+</td>
			<td class="center">420</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>iPod Touch / iPhone</td>
			<td>iPod</td>
			<td class="center">420.1</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Webkit</td>
			<td>S60</td>
			<td>S60</td>
			<td class="center">413</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 7.0</td>
			<td>Win 95+ / OSX.1+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 7.5</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 8.0</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 8.5</td>
			<td>Win 95+ / OSX.2+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.0</td>
			<td>Win 95+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.2</td>
			<td>Win 88+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera 9.5</td>
			<td>Win 88+ / OSX.3+</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Opera for Wii</td>
			<td>Wii</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Nokia N800</td>
			<td>N800</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Presto</td>
			<td>Nintendo DS browser</td>
			<td>Nintendo DS</td>
			<td class="center">8.5</td>
			<td class="center">C/A<sup>1</sup></td>

		</tr>
		<tr class="gradeC">
			<td>KHTML</td>
			<td>Konqureror 3.1</td>
			<td>KDE 3.1</td>
			<td class="center">3.1</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeA">
			<td>KHTML</td>
			<td>Konqureror 3.3</td>
			<td>KDE 3.3</td>
			<td class="center">3.3</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>KHTML</td>
			<td>Konqureror 3.5</td>
			<td>KDE 3.5</td>
			<td class="center">3.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeX">
			<td>Tasman</td>
			<td>Internet Explorer 4.5</td>
			<td>Mac OS 8-9</td>
			<td class="center">-</td>
			<td class="center">X</td>

		</tr>
		<tr class="gradeC">
			<td>Tasman</td>
			<td>Internet Explorer 5.1</td>
			<td>Mac OS 7.6-9</td>
			<td class="center">1</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeC">
			<td>Tasman</td>
			<td>Internet Explorer 5.2</td>
			<td>Mac OS 8-X</td>
			<td class="center">1</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeA">
			<td>Misc</td>
			<td>NetFront 3.1</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeA">
			<td>Misc</td>
			<td>NetFront 3.4</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Dillo 0.8</td>
			<td>Embedded devices</td>
			<td class="center">-</td>
			<td class="center">X</td>

		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Links</td>
			<td>Text only</td>
			<td class="center">-</td>
			<td class="center">X</td>

		</tr>
		<tr class="gradeX">
			<td>Misc</td>
			<td>Lynx</td>
			<td>Text only</td>
			<td class="center">-</td>
			<td class="center">X</td>

		</tr>
		<tr class="gradeC">
			<td>Misc</td>
			<td>IE Mobile</td>
			<td>Windows Mobile 6</td>
			<td class="center">-</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeC">
			<td>Misc</td>
			<td>PSP browser</td>
			<td>PSP</td>
			<td class="center">-</td>
			<td class="center">C</td>

		</tr>
		<tr class="gradeU">
			<td>Other browsers</td>
			<td>All others</td>
			<td>-</td>
			<td class="center">-</td>
			<td class="center">U</td>

		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>Rendering engine</th>
			<th>Browser</th>
			<th>Platform(s)</th>

			<th>Engine version</th>
			<th>CSS grade</th>
		</tr>
	</tfoot>
</table>
<div id="nav">
<h3>Orbital Information</h3>
<a href="#" class="hide">[hide]</a>
<a href="#" class="show">[show]</a>
<ul>
	<li>Distance - 4AU
	<li>Distance from Earth - 2.8 ly
	<li>Habbitable
	<li>Eccentricity - 0.1
	<li>Tilt - 3 degrees
	<li>Length of Day - 33.2 Earth Hours
	<li>Length of Year - 244 Earth Days
	<li>Estimated Age - 4.2 bn years
</ul>
</div>
<hr>
<h3>Surface Information</h3>
<ul>
	<li>Atmospheric Pressure - 100 bar
	<li>Tectonics - Class 3
	<li>Albedo - 0.16
	<li>Average Surface Temp: -21C/-53F
	<li>Surface Radiation: 10 - 350 REM
	<li id="test123" class="readwrite">-1
</ul>
<hr>
<h3>Notable Features</h3>
<ul>
	<li>The Great Canyon
	<li>Blue Crater
	<li>Gin Mountain Range
</ul>
<hr>
<h3>Sattelites [2]</h3>
<ul>
	<li>Titan 
	<li>Io
</ul>
<hr>
<h3>Artificial Sattelites [9]</h3>
<ul>
	<li>Defense Laser[155]        
	<li>Shipyard                  [Dock]
	<li>Battlecruisers[5]         
	<li>Space Station[1]          [Dock]
	<li>Astronomical Telescope[5] [Launch]
	<li>Terraform Sattelite[10] [Launch]
</ul>
<hr>
<h3>Science</h3>
<ul>
	<li>Atmospheric Scan  <-- this function should be included with the Atmosphere list?
	<li>Oceanic Scan
	<li>Meteorological Scan
	<li>Geographical Survey
	<li>Mineral Survey (level 7 - eta 4.5 hrs - retreived information will not exceed level 7 details/quality/breadth/depth )
	<li>Biological Survey
	<li>Energy Scan
	<li>Search for Artifacts
	<li>Collect Microbial and Flora Samples
	<li>Collect Fauna Samples
	<li>Launch Terraform Sattelite
	<li>Launch Sensor Probe
</ul>
<hr>
<h3>Intelligent Life</h3>
<ul>
	<li>Species - J'Grel (insectoid)
	<li>Government Type: Feudal
	<li>Technology Level: 1
	<li>Population: 125.5 million
	<li>Cohesion: 95% (Unified)
	<li>Tension: -5% (Not Perceptible)
	<li>Education
	<li>Health
	<li>Security
		<li>Armies - 9,750 legions
		<li>Militia - 1,500 battalions
	<li>Defense
		<li>Defense Batteries: 0
	<ul>
		<li>Los Angelos [capitol]
		<li>Paris
		<li>Beijing
		<li>New York
		<li>Tokyo
		<li>London
		<li>Berlin
		<li>Rome
		<li>Seoul
	</ul>
</ul>
<hr>
<h3>Surface Operations</h3>
<ul>
	<li>Landing
	<li>Colonize
	<li>Construct Outpost
	<li>Construct Mine
	<li>Collect Mineral
	<li>Collect Food
</ul>
<h3>Structures</h3>
<ul>
	<li>Show Overlay
	<li>Construct Outpost
	<li>Construct Defense Battery (Level 7)
</ul>
<hr>
<h3>Resources</h3>
<ul>
	<li>Resource  Availability   Production
	<li>Water      Rich             
	<li>Deuterium   Rare
	<li>Crystals	Very Rare
	<li>Vegetables  Rich
	<li>Animal Stocks Rich 
</ul>
<hr>
<h3>Diplomacy</h3>
<ul>
	<li>Peace Treaty
	<li>Military Alliance
	<li>Trade Agreement
</ul>
<hr>
<h3>Espionage</h3>
<ul>
	<li>Technology Theft
	<li>Reconnaissance
	<li>Sabatoge
</ul>
<hr>
<h3>Deployments</h3>
<ul>
	<li>Mineral Collection Party [30 - ETA 3.5 Hrs] [recall]
	<li>Espionage Party[2 - ETA 7 days] [recall]
</ul>
<hr>
<h3>Alerts</h3>
!--<ul>
	<li>Surface Weapon Lock <a href="#" data-handler="GUILayout_ButtonClick"><img src="radiationicon" alt="caution radiation leak" width="16" height="16"></a>
	<li>Geological Instability at Away Team Landing Site% <a href="#" data-handler="GUILayout_ButtonClick"><img src="temperatureicon" alt="caution temperature limit" width="16" height="16"></a>
	<li>Sand Storm Approaching Away Team Landing Site% <a href="#" data-handler="GUILayout_ButtonClick"><img src="temperatureicon" alt="caution temperature limit" width="16" height="16"></a>
</ul>
--!
<hr>
