<div class = "columns">
  <div id="level0">
	<div id="componenticon">
		<img src="planet1_quicklook.jpg"height="128" width="128"/>
	</div>
    <div id="level1">
      <div id="level2">
          <div id="main">
			<h3>$componenttypename$</h3>
			<ul class="details" style="padding-left:0px">
				<li>
					<strong class="title">System:</strong>
					<span class="value">Sol</span>
				</li>
				<li>
					<strong class="title">Class:</strong>
					<span class="value">D1 - Rocky Iceball</span>
				</li>
				<li>
				   <strong class="title">Atmosphere:</strong>
				   <span class="value">Nit (77%), Oxy (20%), C Di (1%), Ar (0.7%), Trace (0.3%) (Breathable)</span>
				</li>
			   <li>
					<strong class="title">Mass:</strong>
				   <span class="value">2.52 Earth masses</span>
			   </li>
			   <li>
					<strong class="title">Density:</strong>
				   <span class="value">6331 kg/m3</span>
			   </li>
				<li>
					<strong class="title">Radius:</strong>
					<span class="value">1.52 Earth radius</span>
				</li>
				<li>
					<strong class="title">Surface Gravity:</strong>
					<span class="value">1.08 Earth</span>
				</li>
				<li>
					<strong class="title">Escape Velocity:</strong>
					<span class="value">6.18 km/s</span>
				</li>
				<li>
				   <strong class="title">Percent Land:</strong>
				   <span class="value">23.5%</span>
				</li>
			   <li>
					<strong class="title">Hydrosphere:</strong>
				   <span class="value">ater Lakes 13.5%, Liquid Methane Oceans 60% </span>
			   </li>
			   <li>
					<strong class="title">% Clouds:</strong>
				   <span class="value">37% </span>
			   </li>
			   <li>
					<strong class="title">Magnetic Field:</strong>
				   <span class="value">0.001 Gauss </span>
			   </li>
			   <li>
					<strong class="title">Life:</strong>
				   <span class="value">Primitive</span>
			   </li>
			   <li>
					<strong class="title">Controlled by:</strong>
				   <span class="value">Sol Alliance Since 2245AD</span>
			   </li>
			</ul>
             </div>
           </div>
       </div>
   </div>
   	
<h3>Tasks
	<a href="#" class="hide">[hide]</a>
	<a href="#" class="show">[show]</a>
</h3>
<ul class="details" style="padding-left:0px">
	<li>
		<strong class="title">Mineralogy Survey: [0% - ETA 1.5 Hrs]</strong>
		<span class="value">
		<div class="cprogress" id="showProgress"></div>
		</span> 
	</li>
	<li>
		<strong class="title">Atmospheric Chemical Survey: [99% - ETA .15 Hrs]</strong>
		<span class="title">Hydrogen (71.2%), Helium (28.7%), Other (0.1%)</span>
		<span class="value"><a href="#" class="show">[resume]</a></span>
	</li>
	<li>
		<strong class="title">Electro-Magnetic Survey: [19% - ETA 4.15 Hrs]</strong>
		<span class="title">Polar: (0.95 Gauss), Equatorial (28.7 Gauss), Blberbderb (0.1 Gauss)</span>
		<span class="value">
			<a href="#" class="show" data-handler="GUILayout_ButtonClick">
				<img src="radiationicon" alt="caution radiation leak" width="16" height="16">[cancel]
			</a>
		</span>
	</li>
</ul>
<hr>	
<h3>Mineral Survey Results</h3>
<a href="#" class="hide">[hide]</a>
<a href="#" class="show">[show]</a>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
	<thead>
		<tr>
			<th id="sorting_asc">Metals & Mineral</th>

			<th id="sorting_desc">Surface Deposits</th>
			<th id="sorting">Mineable</th>
			<th id="sorting">Inaccessible</th>
			<th id="sorting"># Mines</th>
		</tr>
	</thead>
	<tbody>

		<tr class="gradeX">
			<td>Titanium</td>
			<td>5M Tons</td>
			<td>21M Tons</td>
			<td> 17M Tons</td>
			<td class="center">11 at 150tons per day.</td>

		</tr>
		<tr class="odd.gradeC">
			<td>Fluorite</td>
			<td>.1 Tons</td>
			<td>.35 Tons</td>
			<td class="center">.75 Tons</td>
			<td class="center">5 at .001 Tons per day.</td>

		</tr>
		<tr class="even.gradeA">
			<td>Tungsten</td>
			<td>Internet
				 Explorer 5.5</td>
			<td>Win 95+</td>
			<td class="center">5.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="odd.gradeA">
			<td>Silicon</td>
			<td>Internet
				 Explorer 6</td>
			<td>Win 98+</td>
			<td class="center">6</td>
			<td class="center">A</td>

		</tr>
		<tr class="even.gradeA">
			<td>Aluminium</td>
			<td>Internet Explorer 7</td>
			<td>Win XP SP2+</td>
			<td class="center">7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Magnesium</td>
			<td>AOL browser (AOL desktop)</td>
			<td>Win XP</td>
			<td class="center">6</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Uranium</td>
			<td>Firefox 1.0</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.7</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Plutonium</td>
			<td>Firefox 1.5</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeA">
			<td>Deuterium</td>
			<td>Firefox 2.0</td>
			<td>Win 98+ / OSX.2+</td>
			<td class="center">1.8</td>
			<td class="center">A</td>

		</tr>
		<tr class="gradeU">
			<td>Other browsers</td>
			<td>All others</td>
			<td>-</td>
			<td class="center">-</td>
			<td class="center">U</td>

		</tr>
	</tbody>
	<tfoot>
		<tr>
			<th>Rendering engine</th>
			<th>Browser</th>
			<th>Platform(s)</th>

			<th>Engine version</th>
			<th>CSS grade</th>
		</tr>
	</tfoot>
</table>
<div id="nav">
<h3>Orbital Information</h3>
<a href="#" class="hide">[hide]</a>
<a href="#" class="show">[show]</a>
<ul>
	<li>Distance - 4AU
	<li>Distance from Earth - 2.8 ly
	<li>Habbitable Zone
	<li>Pariapsis Distance 8,779,942 km
	<li>Apoapsis Distance 10,418,759 km
	<li>Eccentricity - 0.1
	<li>Axial Tilt - 3 degrees
	<li>Length of Day (rotation period) - 1.9 Earth Days
	<li>Length of Year - 244 Earth Days
	<li>Estimated Age - 4.2 bn years
</ul>
</div>
<hr>
<h3>Surface Information</h3>
<ul>
	<li>Atmospheric Pressure - 100 bar
	<li>Tectonics - Class 3
	<li>Albedo - 0.16
	<li>Average Surface Temp: -21C/-53F
	<li>Surface Radiation: 10 - 350 REM
	<li id="test123" class="readwrite">-1
</ul>
<hr>
<h3>Notable Features</h3>
<ul>
	<li>The Great Canyon
	<li>Blue Crater
	<li>Gin Mountain Range
</ul>
<hr>
<h3>Sattelites [21]
	<a href="#" class="hide">[hide]</a>
	<a href="#" class="show">[show]</a>
</h3>
<div class="CSSTableGenerator">
	<table>
		<thead>
			<tr>
				<th id="sorting_asc">Name</th>
				<th id="sorting_desc">Type</th>
				<th id="sorting">Orbital Distance</th>
				<th id="sorting">Mass</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Titan</td>
				<td>Silicate - Rockball</td>
				<td>0.387 AU</td>
				<td> 17M Tons</td>
			</tr>
			<tr>
				<td>Io</td>
				<td>Silicate - Desert</td>
				<td>0.723 AU</td>
				<td>.75 Tons</td>
			</tr>
			<tr>
				<td>Ganymede</td>
				<td>Silicate - Ocean World</td>
				<td>1 AU</td>
				<td>5.5</td>
			</tr>
			<tr>
				<td>Calypso</td>
				<td>Silicate - Desert</td>
				<td>1.524 AU</td>
				<td>6</td>
			</tr>
		</tbody>
	</table>
</div>
<hr>
<h3>Artificial Sattelites [9]</h3>
<ul>
	<li>Defense Laser[155]        
	<li>Shipyard                  [Dock]
	<li>Battlecruisers[5]         
	<li>Space Station[1]          [Dock]
	<li>Astronomical Telescope[5] [Launch]
	<li>Terraform Sattelite[10] [Launch]
</ul>
<hr>
<h3>Science</h3>
<ul>
	<li>Atmospheric Scan  <-- this function should be included with the Atmosphere list?
	<li>Oceanic Scan
	<li>Meteorological Scan
	<li>Geographical Survey
	<li>Mineral Survey (level 7 - eta 4.5 hrs - retreived information will not exceed level 7 details/quality/breadth/depth )
	<li>Biological Survey
	<li>Energy Scan
	<li>Search for Artifacts
	<li>Collect Microbial and Flora Samples
	<li>Collect Fauna Samples
	<li>Launch Terraform Sattelite
	<li>Launch Sensor Probe
</ul>
<hr>
<h3>Archeological Survey</h3>
<a href="#" class="hide">[hide]</a>
<a href="#" class="show">[show]</a>
<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
	<thead>
		<tr>
			<th id="sorting_asc">Site ID</th>

			<th id="sorting_desc">Name</th>
			<th id="sorting">Description</th>
			<th id="sorting">% Explored</th>
			<th id="sorting">Discoveries\Artifacts</th>
		</tr>
	</thead>
	<tbody>

		<tr class="gradeX">
			<td>Trident</td>
			<td>Internet
				 Explorer 4.0</td>
			<td>Win 95+</td>
			<td class="center">4</td>
			<td class="center">C</td>

		</tr>
		<tr class="odd.gradeC">
			<td>Trident</td>
			<td>Internet
				 Explorer 5.0</td>
			<td>Win 95+</td>
			<td class="center">5</td>
			<td class="center">C</td>

		</tr>
		<tr class="even.gradeA">
			<td>Trident</td>
			<td>Internet
				 Explorer 5.5</td>
			<td>Win 95+</td>
			<td class="center">5.5</td>
			<td class="center">A</td>

		</tr>
		<tr class="odd.gradeA">
			<td>Trident</td>
			<td>Internet
				 Explorer 6</td>
			<td>Win 98+</td>
			<td class="center">6</td>
			<td class="center">A</td>

		</tr>
			</tbody>
	<tfoot>
		<tr>
			<th>Site ID</th>
			<th>Name</th>
			<th>Description</th>
			<th>% Explored</th>
			<th>Discoveries\Artifacts</th>
		</tr>
	</tfoot>
</table>
<hr>
<h3>Intelligent Life</h3>
<ul>
	<li>Species - J'Grel (insectoid)
	<li>Government Type: Feudal
	<li>Technology Level: 1
	<li>Population: 125.5 million
	<li>Cohesion: 95% (Unified)
	<li>Tension: -5% (Not Perceptible)
	<li>Education
	<li>Health
	<li>Security
		<li>Armies - 9,750 legions
		<li>Militia - 1,500 battalions
	<li>Defense
		<li>Defense Batteries: 0
	<ul>
		<li>Los Angelos [capitol]
		<li>Paris
		<li>Beijing
		<li>New York
		<li>Tokyo
		<li>London
		<li>Berlin
		<li>Rome
		<li>Seoul
	</ul>
</ul>
<hr>
<h3>Surface Operations</h3>
<ul>
	<li>Landing
	<li>Colonize
	<li>Construct Outpost
	<li>Construct Mine
	<li>Collect Mineral
	<li>Collect Food
</ul>
<h3>Structures</h3>
<ul>
	<li>Show Overlay
	<li>Construct Outpost
	<li>Construct Defense Battery (Level 7)
</ul>
<hr>
<h3>Resources</h3>
<ul>
	<li>Resource  Availability   Production
	<li>Water      Rich             
	<li>Deuterium   Rare
	<li>Crystals	Very Rare
	<li>Vegetables  Rich
	<li>Animal Stocks Rich 
</ul>
<hr>
<h3>Diplomacy</h3>
<ul>
	<li>Peace Treaty
	<li>Military Alliance
	<li>Trade Agreement
</ul>
<hr>
<h3>Espionage</h3>
<ul>
	<li>Technology Theft
	<li>Reconnaissance
	<li>Sabatoge
</ul>
<hr>
<h3>Deployments</h3>
<ul>
	<li>Mineral Collection Party [30 - ETA 3.5 Hrs] [recall]
	<li>Espionage Party[2 - ETA 7 days] [recall]
</ul>
<hr>
</div>
