//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_Camera {
            get {
                object obj = ResourceManager.GetObject("Add Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alarm_bell {
            get {
                object obj = ResourceManager.GetObject("alarm_bell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignToGridHS {
            get {
                object obj = ResourceManager.GetObject("AlignToGridHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_disabled {
            get {
                object obj = ResourceManager.GetObject("back_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap back_enabled {
            get {
                object obj = ResourceManager.GetObject("back_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bar_circle {
            get {
                object obj = ResourceManager.GetObject("bar-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REM this is a good test script
        ///REM only one &quot;script&quot; per line
        ///
        ///bind &apos;mouse1&apos; +leftclick
        ///bind &apos;mouse2&apos; +rightclick
        ///bind &apos;mouse3&apos; +mouselook
        ///bind &apos;mwheelup&apos; zoomin
        ///bind &apos;mwheeldown&apos; zoomout
        ///bind &apos;w&apos; +forward
        ///bind &apos;s&apos; +backward
        ///bind &apos;a&apos; +panleft
        ///bind &apos;d&apos; +panright
        ///bind &apos;leftarrow&apos; +rotateleft
        ///bind &apos;right&apos; +rotateright
        ///bind &apos;up&apos; +panup
        ///bind &apos;downarrow&apos; +pandown
        ///bind &apos;SPACE&apos; +use
        ///bind &apos;LeftControl&apos; +control
        ///bind &apos;RightControl&apos; +control
        ///bind &apos;DELETE&apos; delete
        ///
        ///REM add intentional error lines to [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string binds_editor {
            get {
                return ResourceManager.GetString("binds_editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REM These should not be touched or be accessible to user.
        ///REM Ideally you&apos;d have these in a resource file or encrypted in a PAK
        ///
        ///bind &apos;escape&apos; cancel.
        /// </summary>
        internal static string binds_system {
            get {
                return ResourceManager.GetString("binds_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REM this is a good test script
        ///REM only one &quot;script&quot; per line
        ///
        ///bind &apos;mouse1&apos; +attack
        ///bind &apos;mouse2&apos; +mouselook
        ///bind &apos;mwheelup&apos; zoomin
        ///bind &apos;mwheeldown&apos; zoomout
        ///
        ///bind &apos;w&apos; +forward
        ///bind &apos;s&apos; +backward
        ///bind &apos;a&apos; +strafeleft
        ///bind &apos;d&apos; +straferight
        ///bind &apos;leftarrow&apos; +rotateleft
        ///bind &apos;right&apos; +rotateright
        ///bind &apos;LeftShift&apos; +sprint
        ///
        ///REM bind &apos;leftarrow&apos; +panleft
        ///REM bind &apos;rightarrow&apos; +panright
        ///REM bind &apos;uparrow&apos; +panup
        ///REM bind &apos;downarrow&apos; +pandown
        ///
        ///REM add intentional error lines to see how it handl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string binds_vehicle {
            get {
                return ResourceManager.GetString("binds_vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_icon_16 {
            get {
                object obj = ResourceManager.GetObject("book_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_side_icon_16 {
            get {
                object obj = ResourceManager.GetObject("book_side_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bulb {
            get {
                object obj = ResourceManager.GetObject("bulb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_black {
            get {
                object obj = ResourceManager.GetObject("bullet_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_blue {
            get {
                object obj = ResourceManager.GetObject("bullet_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_green {
            get {
                object obj = ResourceManager.GetObject("bullet_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_orange {
            get {
                object obj = ResourceManager.GetObject("bullet_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_pink {
            get {
                object obj = ResourceManager.GetObject("bullet_pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_purple {
            get {
                object obj = ResourceManager.GetObject("bullet_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_red {
            get {
                object obj = ResourceManager.GetObject("bullet_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_star {
            get {
                object obj = ResourceManager.GetObject("bullet_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bullet_white {
            get {
                object obj = ResourceManager.GetObject("bullet_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_1_icon_16 {
            get {
                object obj = ResourceManager.GetObject("calendar_1_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CanvasScaleHS {
            get {
                object obj = ResourceManager.GetObject("CanvasScaleHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caution_biohazard {
            get {
                object obj = ResourceManager.GetObject("caution_biohazard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caution_high_voltage {
            get {
                object obj = ResourceManager.GetObject("caution_high_voltage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap caution_radiation {
            get {
                object obj = ResourceManager.GetObject("caution_radiation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cert_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cert_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cert_icon_24 {
            get {
                object obj = ResourceManager.GetObject("cert_icon&24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_bar_icon_16 {
            get {
                object obj = ResourceManager.GetObject("chart_bar_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chart_line_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("chart_line_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_unchecked_icon_32 {
            get {
                object obj = ResourceManager.GetObject("checkbox_unchecked_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clipboard_past_icon_16 {
            get {
                object obj = ResourceManager.GetObject("clipboard_past_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap comment16 {
            get {
                object obj = ResourceManager.GetObject("comment16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap corona_yellow {
            get {
                object obj = ResourceManager.GetObject("corona_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crew1_portrait {
            get {
                object obj = ResourceManager.GetObject("crew1_portrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crew1b_portrait {
            get {
                object obj = ResourceManager.GetObject("crew1b_portrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cur_dollar_icon_16 {
            get {
                object obj = ResourceManager.GetObject("cur_dollar_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dashboard_icon_32 {
            get {
                object obj = ResourceManager.GetObject("dashboard_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap db_icon_16 {
            get {
                object obj = ResourceManager.GetObject("db_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doc_empty_icon_16 {
            get {
                object obj = ResourceManager.GetObject("doc_empty_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbar version=&quot;6&quot; fullmenus=&quot;false&quot; fullmenushover=&quot;true&quot; tooltips=&quot;true&quot; scintooltip=&quot;false&quot; animation=&quot;6&quot;&gt;
        ///  &lt;items /&gt;
        ///  &lt;bars&gt;
        ///    &lt;bar name=&quot;plugin bar&quot; candockleft=&quot;true&quot; candockright=&quot;true&quot; candocktop=&quot;true&quot; candockbottom=&quot;true&quot; candockdoc=&quot;false&quot; candocktab=&quot;true&quot; canmaximizefloating=&quot;true&quot; text=&quot;BonedEntity - 9f5e5231-8745-4e76-98c4-0af4290db35f&quot; dockline=&quot;0&quot; grabhandle=&quot;8&quot; menubar=&quot;false&quot; stretch=&quot;true&quot; style=&quot;2&quot; wrapdock=&quot;false&quot; wrapfloat=&quot;true&quot; state=&quot;2&quot; dockside=&quot;4&quot; visible=&quot;true&quot; autohi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editor_definition {
            get {
                return ResourceManager.GetString("editor_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbarlayout version=&quot;6&quot; zorder=&quot;5,6,2,1&quot;&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Top&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Bottom&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;629&quot; dockingside=&quot;Left&quot; originaldocksitesize=&quot;0&quot;&gt;
        ///    &lt;dockcontainer orientation=&quot;0&quot; w=&quot;0&quot; h=&quot;0&quot;&gt;
        ///      &lt;barcontainer w=&quot;626&quot; h=&quot;677&quot;&gt;
        ///        &lt;bar name=&quot;leftDockSiteBar&quot; dockline=&quot;-1&quot; layout=&quot;2&quot; dockoffset=&quot;0&quot; state=&quot;2&quot; dockside=&quot;1&quot; visible=&quot;true&quot; seldocktab=&quot;3&quot;&gt;
        ///          &lt;items&gt;
        ///            &lt;item n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string editor_layout {
            get {
                return ResourceManager.GetString("editor_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Event16 {
            get {
                object obj = ResourceManager.GetObject("Event16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation {
            get {
                object obj = ResourceManager.GetObject("exclamation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_icon_24 {
            get {
                object obj = ResourceManager.GetObject("expand_icon&24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_icon_16 {
            get {
                object obj = ResourceManager.GetObject("eye_icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye_icon_32 {
            get {
                object obj = ResourceManager.GetObject("eye_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_disabled {
            get {
                object obj = ResourceManager.GetObject("forward_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_enabled {
            get {
                object obj = ResourceManager.GetObject("forward_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap globe_2_icon_16 {
            get {
                object obj = ResourceManager.GetObject("globe_2_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hand_pro_icon_16 {
            get {
                object obj = ResourceManager.GetObject("hand_pro_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image {
            get {
                object obj = ResourceManager.GetObject("Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image32 {
            get {
                object obj = ResourceManager.GetObject("image32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jupiterand4moons4ab {
            get {
                object obj = ResourceManager.GetObject("Jupiterand4moons4ab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_icon_16 {
            get {
                object obj = ResourceManager.GetObject("key_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key16 {
            get {
                object obj = ResourceManager.GetObject("key16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///   &lt;section name=&quot;ViewportFloorplanControl&quot;&gt;
        ///      &lt;key name=&quot;showboundingboxes&quot; display=&quot;showboundingboxes&quot; value=&quot;False&quot; type=&quot;&quot; /&gt;
        ///      &lt;key name=&quot;showgrid&quot; display=&quot;showgrid&quot; value=&quot;True&quot; type=&quot;&quot; /&gt;
        ///      &lt;key name=&quot;showfps&quot; display=&quot;Show Frames Per Second&quot; value=&quot;True&quot; type=&quot;System.Boolean&quot; /&gt;
        ///      &lt;key name=&quot;viewmode&quot; display=&quot;View Mode&quot; valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KGBClient {
            get {
                return ResourceManager.GetString("KGBClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_num_icon_48 {
            get {
                object obj = ResourceManager.GetObject("list_num_icon&48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbar version=&quot;6&quot; fullmenus=&quot;false&quot; fullmenushover=&quot;true&quot; tooltips=&quot;true&quot; scintooltip=&quot;false&quot; animation=&quot;6&quot;&gt;
        ///  &lt;items /&gt;
        ///  &lt;bars&gt;
        ///    &lt;bar name=&quot;barStatusBar&quot; candockleft=&quot;false&quot; candockright=&quot;false&quot; candocktop=&quot;false&quot; candockbottom=&quot;true&quot; candockdoc=&quot;false&quot; candocktab=&quot;false&quot; text=&quot;barStatusBar&quot; dockline=&quot;0&quot; dockoffset=&quot;0&quot; grabhandle=&quot;9&quot; menubar=&quot;false&quot; stretch=&quot;true&quot; style=&quot;2&quot; wrapdock=&quot;false&quot; wrapfloat=&quot;true&quot; canundock=&quot;false&quot; state=&quot;2&quot; dockside=&quot;4&quot; visible=&quot;true&quot; custom=&quot;false&quot; canhide=&quot;false&quot; i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lobby_definition {
            get {
                return ResourceManager.GetString("lobby_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbarlayout version=&quot;6&quot; zorder=&quot;5,6,3,1&quot;&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Top&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;147&quot; dockingside=&quot;Bottom&quot; originaldocksitesize=&quot;0&quot;&gt;
        ///    &lt;dockcontainer orientation=&quot;1&quot; w=&quot;0&quot; h=&quot;0&quot;&gt;
        ///      &lt;barcontainer w=&quot;1006&quot; h=&quot;144&quot;&gt;
        ///        &lt;bar name=&quot;barRightDockBar&quot; dockline=&quot;999&quot; layout=&quot;2&quot; dockoffset=&quot;0&quot; state=&quot;2&quot; dockside=&quot;4&quot; fpos=&quot;672,904,237,578&quot; visible=&quot;true&quot;&gt;
        ///          &lt;items&gt;
        ///            &lt;item name=&quot;dockContainerItemRight&quot; origBar=&quot;&quot; origPos=&quot;-1&quot; pos=&quot;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lobby_layout {
            get {
                return ResourceManager.GetString("lobby_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_open_icon_16 {
            get {
                object obj = ResourceManager.GetObject("lock_open_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock_open16 {
            get {
                object obj = ResourceManager.GetObject("lock_open16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lock16 {
            get {
                object obj = ResourceManager.GetObject("lock16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbar version=&quot;6&quot; fullmenus=&quot;false&quot; fullmenushover=&quot;true&quot; tooltips=&quot;true&quot; scintooltip=&quot;false&quot; animation=&quot;6&quot;&gt;
        ///  &lt;items /&gt;
        ///  &lt;bars&gt;
        ///  &lt;/bars&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Top&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Bottom&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Left&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Right&quot; /&gt;
        ///  &lt;popups /&gt;
        ///&lt;/dotnetbar&gt;.
        /// </summary>
        internal static string login_definition {
            get {
                return ResourceManager.GetString("login_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;dotnetbarlayout version=&quot;6&quot; zorder=&quot;7,12,4,2&quot;&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Top&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Bottom&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Left&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;docksite size=&quot;0&quot; dockingside=&quot;Right&quot; originaldocksitesize=&quot;0&quot; /&gt;
        ///  &lt;documents&gt;
        ///    &lt;dockcontainer orientation=&quot;0&quot; w=&quot;0&quot; h=&quot;0&quot;&gt;
        ///      &lt;barcontainer w=&quot;537&quot; h=&quot;609&quot;&gt;
        ///        &lt;bar name=&quot;barDocumentDockBar&quot; dockline=&quot;0&quot; layout=&quot;2&quot; dockoffset=&quot;0&quot; state [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string login_layout {
            get {
                return ResourceManager.GetString("login_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lowerImage {
            get {
                object obj = ResourceManager.GetObject("lowerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail_icon_16 {
            get {
                object obj = ResourceManager.GetObject("mail_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Make_Selection {
            get {
                object obj = ResourceManager.GetObject("Make Selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap method16 {
            get {
                object obj = ResourceManager.GetObject("method16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monitor {
            get {
                object obj = ResourceManager.GetObject("Monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap photo_icon_32 {
            get {
                object obj = ResourceManager.GetObject("photo_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap property16 {
            get {
                object obj = ResourceManager.GetObject("property16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raiseImage {
            get {
                object obj = ResourceManager.GetObject("raiseImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap repair {
            get {
                object obj = ResourceManager.GetObject("repair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap repair2 {
            get {
                object obj = ResourceManager.GetObject("repair2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap round_arrow_left_icon_16 {
            get {
                object obj = ResourceManager.GetObject("round_arrow_left_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap round_arrow_right_icon_16 {
            get {
                object obj = ResourceManager.GetObject("round_arrow_right_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RulerHS {
            get {
                object obj = ResourceManager.GetObject("RulerHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satellite {
            get {
                object obj = ResourceManager.GetObject("satellite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap satellite_dish {
            get {
                object obj = ResourceManager.GetObject("satellite_dish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_icon_24 {
            get {
                object obj = ResourceManager.GetObject("save_icon&24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scull {
            get {
                object obj = ResourceManager.GetObject("scull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search1 {
            get {
                object obj = ResourceManager.GetObject("search1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Select_All_Mesh_Objects {
            get {
                object obj = ResourceManager.GetObject("Select All Mesh Objects", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Selection_Mode {
            get {
                object obj = ResourceManager.GetObject("Selection Mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setting_tools {
            get {
                object obj = ResourceManager.GetObject("setting_tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Show_Heads_Up_Display {
            get {
                object obj = ResourceManager.GetObject("Show Heads Up Display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snap {
            get {
                object obj = ResourceManager.GetObject("snap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_asc {
            get {
                object obj = ResourceManager.GetObject("sort_asc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_asc_disabled {
            get {
                object obj = ResourceManager.GetObject("sort_asc_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_both {
            get {
                object obj = ResourceManager.GetObject("sort_both", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_desc {
            get {
                object obj = ResourceManager.GetObject("sort_desc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_desc_disabled {
            get {
                object obj = ResourceManager.GetObject("sort_desc_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sq_plus_icon_16 {
            get {
                object obj = ResourceManager.GetObject("sq_plus_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop_watch_icon_32 {
            get {
                object obj = ResourceManager.GetObject("stop_watch_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sun_icon_16 {
            get {
                object obj = ResourceManager.GetObject("sun_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap target_icon_16 {
            get {
                object obj = ResourceManager.GetObject("target_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temperature_5 {
            get {
                object obj = ResourceManager.GetObject("temperature_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Textbox {
            get {
                object obj = ResourceManager.GetObject("Textbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap track_icon_16 {
            get {
                object obj = ResourceManager.GetObject("track_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap translate {
            get {
                object obj = ResourceManager.GetObject("translate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turn_On_Move_Manipulator {
            get {
                object obj = ResourceManager.GetObject("Turn On Move-Manipulator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turn_On_Rotation_Manipulator {
            get {
                object obj = ResourceManager.GetObject("Turn On Rotation-Manipulator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Turn_On_Scale_Manipulator {
            get {
                object obj = ResourceManager.GetObject("Turn On Scale-Manipulator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_icon_16 {
            get {
                object obj = ResourceManager.GetObject("users_icon&16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_icon_161 {
            get {
                object obj = ResourceManager.GetObject("users_icon&161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrench1 {
            get {
                object obj = ResourceManager.GetObject("wrench1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrench2 {
            get {
                object obj = ResourceManager.GetObject("wrench2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_icon_32 {
            get {
                object obj = ResourceManager.GetObject("zoom_icon&32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoom_View {
            get {
                object obj = ResourceManager.GetObject("Zoom View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
