//using System;
//using Keystone.Commands;
//using Keystone.EditDataStructures;
//using Keystone.Types;

//namespace Keystone.EditOperations
//{
//    public class AddPointOp : SychronousCommand // a command generated by brushes such as Pencil 
//    {
//        private EditableMesh _mesh;
//        private Vector3f _position;

//        public AddPointOp(EditableMesh target , float x, float y, float z)
//        {
//            _mesh = target;
//            _position.x = x;
//            _position.y = y;
//            _position.z = z;
//        }
        
//        #region ICommand Members
//        public override object Execute()
//        {
//            _mesh.AddVertex(_position.x, _position.y, _position.z);
//            return null;
//        }

//        public override void UnExecute()
//        {
//            throw new NotImplementedException();
//        }
//        #endregion
//    }
//}
