using Lidgren.Network;
using KeyCommon.Messages;

namespace KeyCommon.Messages
{
    /// <summary>
    /// This is typically only used during debugging of client.exe.   
    /// Characters are typically generated by the server, but this command allows the client 
    /// to initiate the generation of characters.
    /// </summary>
    public class Simulation_GenerateCharacters : MessageBase
    {
        public string UserName;
               
        public string ParentID;
        public int Quantity;

       
        public Simulation_GenerateCharacters() : base ((int)Enumerations.Simulation_GenerateCharacters)
        {
        }

        #region IRemotableType Members
        public override void Read(NetBuffer buffer)
        {
            base.Read(buffer);

            UserName = buffer.ReadString();
            ParentID = buffer.ReadString();
            Quantity = buffer.ReadInt32();
        }

        public override void Write(NetBuffer buffer)
        {
            base.Write(buffer);

            buffer.Write(UserName);
            buffer.Write(ParentID);
            buffer.Write(Quantity);
        }
        #endregion
    }
}
